### ISSUE TITLE
Mirror link to download checkpoint ?

### ISSUE THREAD

**Issue by emalti** [jugg1024/Text-Detection-with-FRCN#8]
I can't download it on baidu.com and i can't read the language on this website so is it possible to have it on any other cloud storage service ?

**Comment by joel-simon** [comment]
any update here? Would love to download model.

**Comment by jugg1024** [comment]
@emalti @Sloth6  sorry for waiting! I can't make it to upload to google drive or dropbox, because it always fail(500M file), i'm trying to find somewhere that are available for you.

**Comment by emalti** [comment]
You could try on Hubic

**Comment by jugg1024** [comment]
@emalti Great site! Here is the link https://ovh.to/SivaG2

**Comment by emalti** [comment]
Thanks a lot !

**Comment by rohitbhio** [comment]
Hubic link has expired. Could you upload it again? Thanks
